[2025-08-27T17:25:54.126+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-27T17:25:54.129+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:20:47.043574+00:00 [queued]>
[2025-08-27T17:25:54.131+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:20:47.043574+00:00 [queued]>
[2025-08-27T17:25:54.131+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-08-27T17:25:54.135+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): preprocess_train> on 2025-08-27 17:20:47.043574+00:00
[2025-08-27T17:25:54.137+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2025-08-27T17:25:54.139+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline_simple', 'preprocess_train', 'manual__2025-08-27T17:20:47.043574+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/instructions.py', '--cfg-path', '/tmp/tmpglzh9_b5']
[2025-08-27T17:25:54.140+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask preprocess_train
[2025-08-27T17:25:54.152+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:20:47.043574+00:00 [running]> on host fd074bea2e82
[2025-08-27T17:25:54.170+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ml_pipeline_simple' AIRFLOW_CTX_TASK_ID='preprocess_train' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T17:20:47.043574+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T17:20:47.043574+00:00'
[2025-08-27T17:25:54.170+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-27T17:25:54.175+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-27T17:25:54.175+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/scripts/preprocess_training.py']
[2025-08-27T17:25:54.179+0000] {subprocess.py:86} INFO - Output:
[2025-08-27T17:25:54.456+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-27T17:25:54.457+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/preprocess_training.py", line 4, in <module>
[2025-08-27T17:25:54.457+0000] {subprocess.py:93} INFO -     mmkp = pd.read_csv('/opt/airflow/data/MM_KP.csv') #CHANGE THIS
[2025-08-27T17:25:54.457+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2025-08-27T17:25:54.458+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -     return mapping[engine](f, **self.options)
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -     self._reader = parsers.TextReader(src, **kwds)
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 579, in pandas._libs.parsers.TextReader.__cinit__
[2025-08-27T17:25:54.459+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 668, in pandas._libs.parsers.TextReader._get_header
[2025-08-27T17:25:54.460+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
[2025-08-27T17:25:54.460+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
[2025-08-27T17:25:54.460+0000] {subprocess.py:93} INFO -   File "parsers.pyx", line 2050, in pandas._libs.parsers.raise_parser_error
[2025-08-27T17:25:54.460+0000] {subprocess.py:93} INFO - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 11: invalid start byte
[2025-08-27T17:25:54.480+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-27T17:25:54.484+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:25:54.485+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_pipeline_simple, task_id=preprocess_train, run_id=manual__2025-08-27T17:20:47.043574+00:00, execution_date=20250827T172047, start_date=20250827T172554, end_date=20250827T172554
[2025-08-27T17:25:54.490+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-27T17:25:54.490+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task preprocess_train (Bash command failed. The command returned a non-zero exit code 1.; 188)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:25:54.532+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-27T17:25:54.539+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T17:25:54.541+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
